name: Build container
description: Build and optionally push a container image
inputs:
  arches:
    description: Space-separated list of Go-style architecture names
    default: amd64 arm64
    required: false
  context:
    description: Build context
    default: .
    required: false
  credentials:
    description: Contents of ~/.docker/config.json for pushing
    default:
    required: false
  file:
    description: Path to Dockerfile
    default: Dockerfile
    required: false
  latest-branch:
    description: Branch to tag with "latest"
    default: main
    required: false
  pr-arches:
    description: Space-separated list of architectures to build for PRs
    default:
    required: false
  push:
    description: Optional space-separated list of repositories to push to (ignored for PR builds)
    default:
    required: false
runs:
  using: composite
  steps:
    - name: Compute settings
      shell: bash
      run: |
        if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            tags="${GITHUB_REF#refs/heads/}"
            if [[ "$tags" == "${{ inputs.latest-branch }}" ]]; then
                tags="$tags latest"
            fi
            arches="${{ inputs.arches }}"
        elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            tags="${GITHUB_REF#refs/tags/}"
            arches="${{ inputs.arches }}"
        elif [[ "${GITHUB_REF}" == refs/pull/* ]]; then
            # Don't push anywhere
            tags=
            arches="${{ inputs.pr-arches != '' && inputs.pr-arches || inputs.arches }}"
        else
            echo "Unknown ref: ${GITHUB_REF}"
            exit 1
        fi

        dests=
        for repo in ${{ inputs.push }}; do
            for tag in $tags; do
                dests="$dests $repo:$tag"
            done
        done
        dests="${dests## }"

        platforms=
        for arch in $arches; do
            platforms="$platforms,linux/$arch"
        done
        platforms="${platforms##,}"

        echo "Build platforms: $platforms"
        if [ -n "$dests" ]; then
            echo "Push destinations: $dests"
        else
            echo "Skipping container push"
        fi

        cat >> $GITHUB_ENV <<EOF
        CONTAINER_DESTS=$dests
        CONTAINER_PLATFORMS=$platforms
        EOF
    - name: Install container build dependencies
      if: "env.CONTAINER_PLATFORMS != 'linux/amd64'"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -y install qemu-user-static
    - name: Build container
      shell: bash
      run: |
        podman manifest rm build 2>/dev/null ||:
        set -x
        podman build --manifest build --platform "${CONTAINER_PLATFORMS}" \
            -f "${{ inputs.file }}" "${{ inputs.context }}"
    - name: Push container
      if: "env.CONTAINER_DESTS != ''"
      shell: bash
      run: |
        mkdir -p ~/.docker
        cat > ~/.docker/config.json <<EOF
        ${{ inputs.credentials }}
        EOF

        for dest in ${CONTAINER_DESTS}; do
            echo "==== Pushing $dest"
            podman manifest push build "$dest"
        done
    - name: Remove credentials
      if: ${{ always() }}
      shell: bash
      run: rm -f ~/.docker/config.json
