name: Check diff
description: Compare PR diff to an expected baseline
inputs:
  basedir:
    description: Unmodified source tree (left side of comparison)
    required: true
  patchdir:
    description: Modified source tree (right side of comparison)
    default: .
    required: false
  path:
    description: Only compare the specified path within the trees
    default: .
    required: false
  severity:
    description: Annotation severity (notice, warning, error)
    default: warning
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.basedir }}
    - ${{ inputs.patchdir }}
    - ${{ inputs.path }}
    - "--severity"
    - ${{ inputs.severity }}
