---
name: Run self-test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read

jobs:
  stream-diff:
    name: Run self-test
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run self-test
        run: ./check-diff.py --selftest .
